/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace ThriftCommon
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class Adrelation : TBase
  {
    private string _ad_id;
    private string _lnl_id;
    private string _ad_name;
    private bool _ad_isdeleted;

    public string Ad_id
    {
      get
      {
        return _ad_id;
      }
      set
      {
        __isset.ad_id = true;
        this._ad_id = value;
      }
    }

    public string Lnl_id
    {
      get
      {
        return _lnl_id;
      }
      set
      {
        __isset.lnl_id = true;
        this._lnl_id = value;
      }
    }

    public string Ad_name
    {
      get
      {
        return _ad_name;
      }
      set
      {
        __isset.ad_name = true;
        this._ad_name = value;
      }
    }

    public bool Ad_isdeleted
    {
      get
      {
        return _ad_isdeleted;
      }
      set
      {
        __isset.ad_isdeleted = true;
        this._ad_isdeleted = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool ad_id;
      public bool lnl_id;
      public bool ad_name;
      public bool ad_isdeleted;
    }

    public Adrelation() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.String) {
                Ad_id = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.String) {
                Lnl_id = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 3:
              if (field.Type == TType.String) {
                Ad_name = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 4:
              if (field.Type == TType.Bool) {
                Ad_isdeleted = iprot.ReadBool();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("Adrelation");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (Ad_id != null && __isset.ad_id) {
          field.Name = "ad_id";
          field.Type = TType.String;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(Ad_id);
          oprot.WriteFieldEnd();
        }
        if (Lnl_id != null && __isset.lnl_id) {
          field.Name = "lnl_id";
          field.Type = TType.String;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(Lnl_id);
          oprot.WriteFieldEnd();
        }
        if (Ad_name != null && __isset.ad_name) {
          field.Name = "ad_name";
          field.Type = TType.String;
          field.ID = 3;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(Ad_name);
          oprot.WriteFieldEnd();
        }
        if (__isset.ad_isdeleted) {
          field.Name = "ad_isdeleted";
          field.Type = TType.Bool;
          field.ID = 4;
          oprot.WriteFieldBegin(field);
          oprot.WriteBool(Ad_isdeleted);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("Adrelation(");
      bool __first = true;
      if (Ad_id != null && __isset.ad_id) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Ad_id: ");
        __sb.Append(Ad_id);
      }
      if (Lnl_id != null && __isset.lnl_id) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Lnl_id: ");
        __sb.Append(Lnl_id);
      }
      if (Ad_name != null && __isset.ad_name) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Ad_name: ");
        __sb.Append(Ad_name);
      }
      if (__isset.ad_isdeleted) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Ad_isdeleted: ");
        __sb.Append(Ad_isdeleted);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
