/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace ThriftCommon
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class BlackList : TBase
  {
    private string _bl_id;
    private IdentifyType _bl_identify_type;
    private string _bl_identify_no;
    private string _bl_name;
    private string _bl_sex;
    private string _bl_reason;
    private bool _bl_isdeleted;

    public string Bl_id
    {
      get
      {
        return _bl_id;
      }
      set
      {
        __isset.bl_id = true;
        this._bl_id = value;
      }
    }

    /// <summary>
    /// 
    /// <seealso cref="IdentifyType"/>
    /// </summary>
    public IdentifyType Bl_identify_type
    {
      get
      {
        return _bl_identify_type;
      }
      set
      {
        __isset.bl_identify_type = true;
        this._bl_identify_type = value;
      }
    }

    public string Bl_identify_no
    {
      get
      {
        return _bl_identify_no;
      }
      set
      {
        __isset.bl_identify_no = true;
        this._bl_identify_no = value;
      }
    }

    public string Bl_name
    {
      get
      {
        return _bl_name;
      }
      set
      {
        __isset.bl_name = true;
        this._bl_name = value;
      }
    }

    public string Bl_sex
    {
      get
      {
        return _bl_sex;
      }
      set
      {
        __isset.bl_sex = true;
        this._bl_sex = value;
      }
    }

    public string Bl_reason
    {
      get
      {
        return _bl_reason;
      }
      set
      {
        __isset.bl_reason = true;
        this._bl_reason = value;
      }
    }

    public bool Bl_isdeleted
    {
      get
      {
        return _bl_isdeleted;
      }
      set
      {
        __isset.bl_isdeleted = true;
        this._bl_isdeleted = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool bl_id;
      public bool bl_identify_type;
      public bool bl_identify_no;
      public bool bl_name;
      public bool bl_sex;
      public bool bl_reason;
      public bool bl_isdeleted;
    }

    public BlackList() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.String) {
                Bl_id = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.I32) {
                Bl_identify_type = (IdentifyType)iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 3:
              if (field.Type == TType.String) {
                Bl_identify_no = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 4:
              if (field.Type == TType.String) {
                Bl_name = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 5:
              if (field.Type == TType.String) {
                Bl_sex = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 6:
              if (field.Type == TType.String) {
                Bl_reason = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 7:
              if (field.Type == TType.Bool) {
                Bl_isdeleted = iprot.ReadBool();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("BlackList");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (Bl_id != null && __isset.bl_id) {
          field.Name = "bl_id";
          field.Type = TType.String;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(Bl_id);
          oprot.WriteFieldEnd();
        }
        if (__isset.bl_identify_type) {
          field.Name = "bl_identify_type";
          field.Type = TType.I32;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32((int)Bl_identify_type);
          oprot.WriteFieldEnd();
        }
        if (Bl_identify_no != null && __isset.bl_identify_no) {
          field.Name = "bl_identify_no";
          field.Type = TType.String;
          field.ID = 3;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(Bl_identify_no);
          oprot.WriteFieldEnd();
        }
        if (Bl_name != null && __isset.bl_name) {
          field.Name = "bl_name";
          field.Type = TType.String;
          field.ID = 4;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(Bl_name);
          oprot.WriteFieldEnd();
        }
        if (Bl_sex != null && __isset.bl_sex) {
          field.Name = "bl_sex";
          field.Type = TType.String;
          field.ID = 5;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(Bl_sex);
          oprot.WriteFieldEnd();
        }
        if (Bl_reason != null && __isset.bl_reason) {
          field.Name = "bl_reason";
          field.Type = TType.String;
          field.ID = 6;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(Bl_reason);
          oprot.WriteFieldEnd();
        }
        if (__isset.bl_isdeleted) {
          field.Name = "bl_isdeleted";
          field.Type = TType.Bool;
          field.ID = 7;
          oprot.WriteFieldBegin(field);
          oprot.WriteBool(Bl_isdeleted);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("BlackList(");
      bool __first = true;
      if (Bl_id != null && __isset.bl_id) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Bl_id: ");
        __sb.Append(Bl_id);
      }
      if (__isset.bl_identify_type) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Bl_identify_type: ");
        __sb.Append(Bl_identify_type);
      }
      if (Bl_identify_no != null && __isset.bl_identify_no) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Bl_identify_no: ");
        __sb.Append(Bl_identify_no);
      }
      if (Bl_name != null && __isset.bl_name) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Bl_name: ");
        __sb.Append(Bl_name);
      }
      if (Bl_sex != null && __isset.bl_sex) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Bl_sex: ");
        __sb.Append(Bl_sex);
      }
      if (Bl_reason != null && __isset.bl_reason) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Bl_reason: ");
        __sb.Append(Bl_reason);
      }
      if (__isset.bl_isdeleted) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Bl_isdeleted: ");
        __sb.Append(Bl_isdeleted);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
