/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace ThriftCommon
{
  public enum DbOprator
  {
    Add = 0,
    Update = 1,
    Delete = 2,
  }
}
