/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace ThriftCommon
{
  public enum IdentifyType
  {
    IdCard = 0,
    Employee = 1,
    Ohter = 2,
  }
}
