/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace ThriftCommon
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class ReaderList : TBase
  {
    private string _reader_id;
    private string _reader_name;

    public string Reader_id
    {
      get
      {
        return _reader_id;
      }
      set
      {
        __isset.reader_id = true;
        this._reader_id = value;
      }
    }

    public string Reader_name
    {
      get
      {
        return _reader_name;
      }
      set
      {
        __isset.reader_name = true;
        this._reader_name = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool reader_id;
      public bool reader_name;
    }

    public ReaderList() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.String) {
                Reader_id = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.String) {
                Reader_name = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("ReaderList");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (Reader_id != null && __isset.reader_id) {
          field.Name = "reader_id";
          field.Type = TType.String;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(Reader_id);
          oprot.WriteFieldEnd();
        }
        if (Reader_name != null && __isset.reader_name) {
          field.Name = "reader_name";
          field.Type = TType.String;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(Reader_name);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("ReaderList(");
      bool __first = true;
      if (Reader_id != null && __isset.reader_id) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Reader_id: ");
        __sb.Append(Reader_id);
      }
      if (Reader_name != null && __isset.reader_name) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Reader_name: ");
        __sb.Append(Reader_name);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
