/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace ThriftCommon
{
  public enum Status
  {
    None = 0,
    Visiting = 1,
    Leave = 2,
    NoComeBack = 3,
    LostCard = 4,
  }
}
